const http=require('http'), fs=require('fs'), path=require('path'), crypto=require('crypto'), {execFile}=require('child_process');
const DATA='/app/data'; fs.mkdirSync(DATA,{recursive:true});
const STATE=path.join(DATA,'state.json');
function uuid(){return crypto.randomUUID()}
let state;
try{state=JSON.parse(fs.readFileSync(STATE,'utf8'))}catch{state={users:[{username:'admin',passwordHash:hash('admin1323')}],clients:[{id:uuid(),name:'WebSocket TLS'},{id:uuid(),name:'HTTPUpgrade TLS'},{id:uuid(),name:'XHTTP TLS'}]}; save()}
function hash(s){return crypto.createHash('sha256').update(s).digest('hex')}
function save(){fs.writeFileSync(STATE,JSON.stringify(state,null,2))}
const sessions=new Map();
function send(res,code,type,body){res.writeHead(code,{'content-type':type,'cache-control':'no-store'});res.end(body)}
function cookie(req){return (req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('sid='))?.slice(4)}
function auth(req){return sessions.has(cookie(req))}
function json(res,o,code=200){send(res,code,'application/json; charset=utf-8',JSON.stringify(o))}
function body(req){return new Promise((resolve,reject)=>{let b='';req.on('data',c=>b+=c);req.on('end',()=>{try{resolve(b?JSON.parse(b):{})}catch(e){reject(e)}});req.on('error',reject)})}
function domain(req){return (req.headers.host||'').split(':')[0]||'YOUR-RAILWAY-DOMAIN'}
function configs(req){const d=domain(req); return state.clients.map((c,i)=>{const paths=['/ws-vless','/hu-vless','/xhttp-vless']; const types=['ws','httpupgrade','xhttp']; const q=new URLSearchParams({type:types[i],security:'tls',encryption:'none',path:paths[i],sni:d}); if(i===0)q.set('host',d); if(i===1)q.set('host',d); if(i===2){q.set('mode','auto');q.set('host',d)} return {name:c.name,uuid:c.id,transport:types[i],path:paths[i],url:`vless://${c.id}@${d}:443?${q.toString()}#${encodeURIComponent(c.name)}`}})}
function writeXray(req){const clients=state.clients; const base=(i,method,settings,port)=>({listen:'127.0.0.1',port,protocol:'vless',settings:{clients:[{id:clients[i].id,email:clients[i].name}],decryption:'none'},streamSettings:{network:method,security:'none',...settings},tag:['vless-ws','vless-hu','vless-xhttp'][i]}); const cfg={log:{loglevel:'warning',access:'/app/runtime/access.log',error:'/app/runtime/error.log'},inbounds:[base(0,'ws',{wsSettings:{path:'/ws-vless'}},10001),base(1,'httpupgrade',{httpupgradeSettings:{path:'/hu-vless'}},10002),base(2,'xhttp',{xhttpSettings:{path:'/xhttp-vless',mode:'auto'}},10003)],outbounds:[{protocol:'freedom',tag:'direct'},{protocol:'blackhole',tag:'blocked'}]}; fs.mkdirSync('/app/runtime',{recursive:true}); fs.writeFileSync('/app/runtime/xray.json',JSON.stringify(cfg,null,2)); return cfg}
let lastReq={headers:{host:process.env.RAILWAY_PUBLIC_DOMAIN||'YOUR-RAILWAY-DOMAIN'}}; writeXray(lastReq);
const server=http.createServer(async(req,res)=>{try{if(req.url==='/health'){return json(res,{ok:true,panel:true})} if(req.url==='/api/login'&&req.method==='POST'){const b=await body(req); if(b.username==='admin'&&hash(String(b.password||''))===state.users[0].passwordHash){const sid=crypto.randomBytes(32).toString('hex');sessions.set(sid,{at:Date.now()});res.writeHead(200,{'content-type':'application/json','set-cookie':`sid=${sid}; HttpOnly; Secure; SameSite=Lax; Path=/`});return res.end(JSON.stringify({ok:true}))} return json(res,{ok:false,error:'Invalid credentials'},401)} if(req.url==='/api/logout'){sessions.delete(cookie(req));res.writeHead(200,{'set-cookie':'sid=; Max-Age=0; Path=/'});return res.end('{}')} if(!auth(req))return json(res,{error:'Unauthorized'},401); if(req.url==='/api/configs'){writeXray(req);return json(res,{domain:domain(req),configs:configs(req)})} if(req.url==='/api/status'){return json(res,{ok:true,domain:domain(req),xrayConfig:'/app/runtime/xray.json'})} if(req.url==='/api/password'&&req.method==='POST'){const b=await body(req);if(String(b.password||'').length<8)return json(res,{error:'Password must be at least 8 characters'},400);state.users[0].passwordHash=hash(String(b.password));save();return json(res,{ok:true})} if(req.url==='/'){return fs.createReadStream('/app/public/index.html').pipe(res)} return send(res,404,'text/plain','Not found')}catch(e){console.error(e);json(res,{error:'Server error'},500)}});
server.listen(process.env.PANEL_PORT||3000,'0.0.0.0',()=>console.log('Panel listening'));
